# Tested on Ubuntu 22.04 (LTS) x64
- name: Update and Upgrade apt packages and reboot
  hosts: archesservers
  remote_user: root

  tasks:
    - name: Update apt-get repo, cache and upgrade
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Slow reboot
      ansible.builtin.reboot:
        reboot_timeout: 3600
