- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packagename }}"
    state: present
    force_apt_get: true
    update_cache: true
  vars:
    packagename:
      - build-essential
      - curl
      - postfix
      - mailutils
      - unattended-upgrades
      - rsync
      - rsnapshot
      - tmux
      - python3-pip
      - libxml2-dev
      - libproj-dev
      - libjson-c-dev
      - xsltproc
      - docbook-xsl
      - docbook-mathml
      - libgdal-dev
      - libpq-dev
      - python3-dev
      - python3-venv
