# Tested on Ubuntu 22.04 (LTS) x64
- name: Update and Upgrade apt packages and reboot
  hosts: archesservers
  remote_user: root

  tasks:
    - name: Update apt
      block:
        - name: Update
          ansible.builtin.import_tasks:
            file: ../tasks/update.yml
    - name: Install apt packages
      block:
        - name: Apt packages
          ansible.builtin.import_tasks:
            file: ../tasks/install-apt-packages.yml
